### ISSUE TITLE
Exception thrown when saving a scene: "TypeError: Cannot read properties of null (reading 'id')" 

### ISSUE THREAD

**Issue by watermelonwolverine** [theripper93/Levels#105]
When saving a scene the following exception is thrown:

```
TypeError: Cannot read properties of null (reading 'id')
[Detected 1 package: levels]
    at Object.fn (backgroundHandler.js:25:42)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at ClientDatabaseBackend.callback (foundry.js:12767:13)
    at foundry.js:12715:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:12715:33)
    at ClientDatabaseBackend._updateDocuments (foundry.js:12592:17)
    at async Scene.updateDocuments (commons.js:6128:23)
    at async Scene.update (commons.js:6225:23)
    at async SceneConfig._onSubmit (foundry.js:5874:7)
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | 🎁Hooks.onError#lib-wrapper | @ | listeners.js:137
  | 🎁Hooks.onError#0 | @ | libWrapper-wrapper.js:187
  | #call | @ | foundry.js:728
  | callAll | @ | foundry.js:681
  | callback | @ | foundry.js:12767
  | (anonymous) | @ | foundry.js:12715
  | _handleUpdateDocuments | @ | foundry.js:12715
  | _updateDocuments | @ | foundry.js:12592
  | await in _updateDocuments (async) |   |  
  | update | @ | commons.js:6771
  | await in update (async) |   |  
  | updateDocuments | @ | commons.js:6128
  | update | @ | commons.js:6225
  | _updateObject | @ | foundry.js:66180
  | _onSubmit | @ | foundry.js:5874
```

**Comment by watermelonwolverine** [comment]
```
Versions:
  Foundry: 10.287
  System: dnd5e version 2.0.3
User:
  Role: GAMEMASTER
Settings:
  Disable_Canvas: Disabled
  Max_FPS: 60
  Token_Drag_Vision: Disabled
  Performance_Mode: 2
  Token_Vision_Animation: Enabled
  Light_Source_Animation: Enabled
  Zoomed_Texture_Antialiasing: Enabled
  Animate_Roll_Tables: Enabled
Scene:
  Walls: 15
  Lights: 0
  Tokens: 0
  Tiles: undefined
  Sounds: 0
  Drawings: 0
  Notes: 0
  Dimensions: 7680 x 7680
  Background: undefined x undefined
  Foreground: undefined x undefined
WebGL:
  Context: WebGL2RenderingContext
  GL_Vendor: WebKit
  Renderer: WebKit WebGL
  Unmasked_Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 960M Direct3D11 vs_5_0 ps_5_0, D3D11)
  WebGL_Version: WebGL 2.0 (OpenGL ES 3.0 Chromium)
  MAX_TEXTURE_SIZE: 16384
  MAX_RENDERBUFFER: 16384
Database:
  Actors: 0
  Items: 0
  Scenes: 29
  Journals: 0
  Tables: 0
  Chat: 0
  Macros: 7
Data_Sizes:
  Actors: 2 Bytes
  Items: 2 Bytes
  Scenes: 1.1 MB
  Journals: 2 Bytes
  Tables: 2 Bytes
  Chat: 2 Bytes
  Macros: 6.39 KB
Browser:
  Platform: Win32
  Vendor: Google Inc.
  Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Memory:
  Heap_Limit: 4 GB
  Heap_Total: 160.76 MB
  Heap_Used: 137.14 MB
Load:
  World_Size: 1.1 MB
  Scene_Size: 1.95 MB
Modules:
  Total: 62
  Enabled: 52
Active_Modules:
  about-time: About Time v10.0.1
  advanced-drawing-tools: Advanced Drawing Tools v2.0.2
  advanced-macros: Advanced Macros vv1.17
  autoanimations: Automated Animations v3.3.16
  betterroofs: Better Roofs v1.7.3
  combatbooster: Combat Booster: Turn Marker, Recent Actions and more v3.2
  compendium-folders: Compendium Folders v2.5.3
  dae: Dynamic effects using Active Effects v10.0.9
  ddb-importer: D&D Beyond Importer v3.1.13
  ddb-importer-compendiums: DDB Importer Compendiums v1.0.0
  debug-report: Debug Report Generator v0.1.5
  df-manual-rolls: DF Manual Rolls v2.3.1
  df-settings-clarity: DF Settings Clarity v3.2.1
  dfreds-convenient-effects: DFreds Convenient Effects v3.0.1
  dice-calculator: Dice Tray v1.5.2
  dice-so-nice: Dice So Nice! v4.6.3
  dice-tooltip: Dice Tooltip - DnD5e v2.3.1
  disable-mouse-wheel-sliders: Disable Mouse Wheel Control for Sliders v1.2.5
  force-client-controls: Force Client Controls v1.0.4
  force-client-settings: Force Client Settings v2.3.2
  forien-quest-log: Forien's Quest Log v0.7.11
  foundryvtt-simple-calendar: Simple Calendar v2.1.27
  fxmaster: FXMaster v3.5.0
  itemacro: Item Macro v1.8.0
  jb2a_patreon: JB2A - Patreon Complete Collection v0.4.7
  levels: Levels v3.2.7
  lib-changelogs: Changelogs & Conflicts v0.7.7
  lib-wrapper: libWrapper v1.12.10.0
  lmrtfy: Let Me Roll That For You! v3.0.3
  mcc: Module Compatibility Checker v1.3.2
  midi-qol: Midi QOL v10.0.14
  multi-token-edit: Mass Edit v1.20.0
  pause-icon: Alternative Pause Icon v1.0.3
  perfect-vision: Perfect Vision v4.0.26
  permission_viewer: Ownership Viewer v0.10.0
  popout: PopOut! v2.9
  select-tool-everywhere: Select tool everywhere v1.4.0
  sequencer: Sequencer v2.3.8
  shared-data: Shared Data v1.0.0
  smalltime: SmallTime v1.15.3
  smarttarget: Smart Target v0.9.3
  socketlib: socketlib v1.0.12
  tidy5e-sheet: Tidy5e Sheet v0.6.6
  times-up: Times Up v10.0.2
  token-animation-tools: Token Animation Tools v1.3.1.0
  token-attacher: Token Attacher v4.5.2
  token-chat-link: Token Chat Link v1.1.0
  token-variants: Token Variant Art v4.3.0
  token-z: Token Z v0.7.6
  tokenmagic: Token Magic FX v0.6.1.2
  vtta-tokenizer: Tokenizer v3.9.5
  wall-height: Wall Height v4.7.8
```

**Comment by theripper93** [comment]
with game canvas disabled, Levels will most likely throw errors. i won't provide fixes for these, you can ignore them since with canvas disabled the module does nothing anyways

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
