### ISSUE TITLE
Error detected in Module from Lib Wrapper

### ISSUE THREAD

**Issue by timothyCoxon** [theripper93/Levels#69]
**Could not find target 'LightSource.prototype._renderTexture': Could not find root scope 'LightSource'.**

I've been trying to identify what is causing this but have not managed to. I do have midi-qol on, but player control owned hidden tokens is disabled.
Not even sure if this is actually something to worry about...

`[Detected 1 package: levels]
    at oe (http://192.168.0.89:30000/modules/lib-wrapper/lib-wrapper.js:1:42552)
    at ce (http://192.168.0.89:30000/modules/lib-wrapper/lib-wrapper.js:1:42854)
    at Function.🎁register [as register] (http://192.168.0.89:30000/modules/lib-wrapper/lib-wrapper.js:1:45951)
    at http://192.168.0.89:30000/modules/levels/scripts/config.js:73:14
    at Function._call (eval at <anonymous> (http://192.168.0.89:30000/modules/lib-wrapper/lib-wrapper.js:1:49983), <anonymous>:4:14)
    at Function.callAll (http://192.168.0.89:30000/scripts/foundry.js:153:12)
    at Game.initialize (http://192.168.0.89:30000/scripts/foundry.js:4274:11)
    at Z.🎁call_wrapped [as call_wrapped] (http://192.168.0.89:30000/modules/lib-wrapper/lib-wrapper.js:1:30069)
    at Game.🎁libWrapperInit (http://192.168.0.89:30000/modules/lib-wrapper/lib-wrapper.js:1:50887)`

**Comment by timothyCoxon** [comment]
Actually, I should amend the "actually something to worry about". When I activate Levels it doesn't display the canvas at all.

**Comment by timothyCoxon** [comment]
I did just run a new world.. foundryvtt 0.8.9, dnd5e 1.5.5 only 4 active modules being levels and it's dependencies and got the same issue.

**Comment by theripper93** [comment]
Wild guess, you updated to v9 then downgraded and you are running the v9 version on levels, uninstall and reinstall

**Comment by timothyCoxon** [comment]
For a wild guess, that's fairly spot on... Let me try that ;)

**Comment by timothyCoxon** [comment]
Yup.. That's fixed it :) thank you :)
